# Generated by Django 3.1 on 2020-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_key', models.CharField(max_length=30)),
                ('fernet_key', models.CharField(max_length=60)),
            ],
        ),
    ]
